steps:
- id: 'update discord bot vm'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      PROJECT_ID=$(gcloud config list --format 'value(core.project)' 2>/dev/null)
      gcloud builds submit --tag gcr.io/"${PROJECT_ID}"/mintposterbot
      gcloud compute instances update-container haspass-expo --zone=europe-west1-b --container-image=gcr.io/spartan-theorem-328817/mintposterbot:latest

